export { default as PageAuth } from '@components/pages/PageAuth'
export { default as PageProfile } from '@components/pages/PageProfile'
export { default as PageSettings } from '@components/pages/PageSettings'
export { default as PageResetPassword } from '@components/pages/PageResetPassword'
export { default as ResetPasswordConfirm } from '@components/pages/ResetPasswordConfirm'
